# NFL Coaching Tree 
#### This project focuses on tracing the lineage of NFL head coaching trees, mapping out how current and former coaches are connected through past coaching relationships. By analyzing these coaching trees, it becomes apparent how coaching philosophies, strategies, and networks have evolved and spread across the league over time. The goal is to visualize these connections and highlight influential coaching figures who have shaped the modern NFL. In addition, by viewing each staff's win total and potential awards received, we can get a better insight into how big of an impact a successful team played on the staff's individual success in the future

# First, we will load in all the necessary packages
#### These packages will help us get a better understanding of the dataset and of all the variables that are at play.

In [2]:
# Imports 
import pandas as pd
import numpy as np
import pandasql as ps

### We can load all datasets into a pandas library and view what's inside
#### First is the coaches csv file. It contains information about a coach and each member on their staff alongside their role. Also contains info on how long each member was a part of the staff under the head coach alongside how the team's

In [12]:
hc = pd.read_csv('NFL_Coaches.csv')
ps.sqldf("select * from hc order by ly_a desc")

,Head_Coach,Coach,weight,group,group_count,lrole,tW,tPyW,tg_hc,ftm,...,fy_a,ly_a,TYr,nw,pyw500,above500,odo,cord,lodo,lcord
0,Frank Reich,Nick Sirianni,3,OC,3,OC,40,41.60,75,IND,...,2018,2020,3,1.0,1,1,1,1,1,1
1,John Harbaugh,David Culley,6,aOC,4,aOC,147,151.20,242,BAL,...,2019,2020,2,3.0,1,1,1,0,1,0
2,Kyle Shanahan,Robert Saleh,4,DC,4,DC,52,54.83,98,SF,...,2017,2020,4,1.0,1,1,2,1,2,1
3,Mike Vrabel,Arthur Smith,3,OC,2,OC,48,43.91,82,TEN,...,2018,2020,3,1.0,1,1,1,1,1,1
4,Sean McVay,Brandon Staley,1,DC,1,DC,60,57.95,98,LA,...,2020,2020,1,1.0,1,1,2,1,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
627,Harry Gilmer,Joe Schmidt,1,aDC,1,aDC,4,3.71,14,DET,...,1966,1966,1,1.0,0,0,2,0,2,0
628,Harry Gilmer,John North,1,aOC,1,aOC,4,3.71,14,DET,...,1966,1966,1,1.0,0,0,1,0,1,0
629,John Rauch,Bill Walsh,1,aOC,1,aOC,40,37.97,70,LV,...,1966,1966,1,1.0,1,1,1,0,1,0
630,Norb Hecker,Tom Fears,1,OC,1,OC,4,3.81,31,ATL,...,1966,1966,1,1.0,0,0,1,1,1,1
631,Weeb Ewbank,Chuck Knox,1,aOC,1,aOC,56,57.96,112,NYJ,...,1966,1966,1,1.0,1,1,1,0,1,0

#### Next, we can load in the wins csv file. It contains stats about a head coach's season with a tema such as wins/losses, total points scored for and against. In addition, it also contains whether or not a coach won/appeared in the superbowl that year, and if they received a coach of the year award

In [4]:
wins = pd.read_csv('wins.csv')
ps.sqldf("select * from wins where Tm = 'DET' order by Season desc")

,Season,Coach,Tm,Win,Loss,Tie,PF,PA,Total,fwk,...,yrs_hc,ftm,ltm,mpwpct,sb,sba,coy,name,pywins,awins
0,2022,Dan Campbell,DET,9,8,0,453,427,17,1,...,3,MIA,DET,0.486228,0,0,0,Dan Campbell's,9.094395,9.000000
1,2021,Dan Campbell,DET,3,13,1,325,467,17,1,...,3,MIA,DET,0.486065,0,0,0,Dan Campbell's,5.057843,3.500000
2,2020,Darrell Bevell,DET,1,4,0,125,191,5,13,...,2,DET,JAX,0.484773,0,0,0,Darrell Bevell's,4.556030,3.400000
3,2020,Matt Patricia,DET,4,7,0,252,328,11,1,...,3,DET,DET,0.484773,0,0,0,Matt Patricia's,5.928144,6.181818
4,2019,Matt Patricia,DET,3,12,1,341,423,16,1,...,3,DET,DET,0.480646,0,0,0,Matt Patricia's,6.375458,3.718750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,1970,Joe Schmidt,DET,10,4,0,347,202,14,1,...,6,DET,DET,0.474670,0,0,0,Joe Schmidt's,13.308313,12.142857
58,1969,Joe Schmidt,DET,9,4,1,259,188,14,1,...,6,DET,DET,0.505827,0,0,0,Joe Schmidt's,11.580485,11.535714
59,1968,Joe Schmidt,DET,4,8,2,207,241,14,1,...,6,DET,DET,0.481113,0,0,0,Joe Schmidt's,6.984563,6.071429
60,1967,Joe Schmidt,DET,5,7,2,260,259,14,1,...,6,DET,DET,0.501042,0,0,0,Joe Schmidt's,8.538815,7.285714
61,1966,Harry Gilmer,DET,4,9,1,206,317,14,1,...,1,DET,DET,0.487475,0,0,0,Harry Gilmer's,4.500399,5.464286

#### We can join our coaches and win tables on the season in order to paint a full picture of what exactly each season entailed in terms of their overall performance, alongside who was on the team.

In [5]:
staff = ps.sqldf("""
WITH RECURSIVE year_sequence AS (
  -- Base case
  SELECT 
    Head_Coach,
    Coach,
    fy_a AS coaching_year,
    ly_a AS end_year,
    lrole
  FROM 
    hc
  
  UNION ALL
  
  -- Recursive case
  SELECT
    Head_Coach,
    Coach,
    coaching_year + 1,
    end_year,
    lrole
  FROM 
    year_sequence
  WHERE 
    coaching_year < end_year
)

SELECT 
  Head_Coach,
  Coach,
  coaching_year,
  lrole
FROM 
  year_sequence
ORDER BY 
  Head_Coach, Coach, coaching_year
""")
staff

       Head_Coach           Coach  coaching_year lrole
0       Adam Gase    Vance Joseph           2016    DC
1         Al Groh  Ken Whisenhunt           2000  aSTC
2         Al Groh      Mike Nolan           2000    DC
3         Al Groh     Todd Bowles           2000   aDC
4         Al Groh      Todd Haley           2000   aOC
...           ...             ...            ...   ...
2072  Weeb Ewbank   Walt Michaels           1967   aDC
2073  Weeb Ewbank   Walt Michaels           1968   aDC
2074  Weeb Ewbank   Walt Michaels           1969   aDC
2075  Weeb Ewbank   Walt Michaels           1970   aDC
2076  Weeb Ewbank   Walt Michaels           1971   aDC

[2077 rows x 4 columns]

#### Now we can get an exact breakdown of a single head coach's staff for an entire specific season, and use this to better build our eventual coaching tree

In [14]:
final = ps.sqldf("select staff.coaching_year, staff.Head_Coach, staff.Coach, staff.lrole as role, wins.Tm as team, wins.Win, wins.Loss, wins.Tie from staff left join wins on staff.coaching_year=wins.Season and staff.Head_Coach = wins.Coach")
final

      coaching_year   Head_Coach           Coach  role team   Win  Loss  Tie
0              2016    Adam Gase    Vance Joseph    DC  MIA  10.0   6.0  0.0
1              2000      Al Groh  Ken Whisenhunt  aSTC  NYJ   9.0   7.0  0.0
2              2000      Al Groh      Mike Nolan    DC  NYJ   9.0   7.0  0.0
3              2000      Al Groh     Todd Bowles   aDC  NYJ   9.0   7.0  0.0
4              2000      Al Groh      Todd Haley   aOC  NYJ   9.0   7.0  0.0
...             ...          ...             ...   ...  ...   ...   ...  ...
2072           1967  Weeb Ewbank   Walt Michaels   aDC  NYJ   8.0   5.0  1.0
2073           1968  Weeb Ewbank   Walt Michaels   aDC  NYJ  11.0   3.0  0.0
2074           1969  Weeb Ewbank   Walt Michaels   aDC  NYJ  10.0   4.0  0.0
2075           1970  Weeb Ewbank   Walt Michaels   aDC  NYJ   4.0  10.0  0.0
2076           1971  Weeb Ewbank   Walt Michaels   aDC  NYJ   6.0   8.0  0.0

[2077 rows x 8 columns]

In [15]:
final.to_csv('Completed_Coaching_Tree')